#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Symfony\Component\Console\Application;
use Scraper\Commands\ScraperCommand;

$app = new Application();
$app->add(new ScraperCommand());
$app->run();